name: Build ZMK Firmware
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZMK Firmware
        uses: zmkfirmware/zmk-build-arm@stable
        with:
          board: nice_nano_v2
          shield: charybdis_4x6_left charybdis_4x6_right
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.uf2
