name: Build and Release Firmware
on:
  push:
    tags:
      - 'v*.*.*' # Trigger on release tags (e.g., v1.0.0)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZMK Firmware
        uses: zmkfirmware/zmk-build-arm@stable
        with:
          board: charybdis_3x5
          shield: your_keymap
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.uf2
